informations/urls.py
from django.urls import path
from django.shortcuts import redirect

urlpatterns = [
    path('home/', lambda x : redirect('home')),
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from informations.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name="home"),
    path('informations/', include('informations.urls')),
]
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

informations/models.py
from django.db import models


class ProfessionnalProfile(models.Model):
    description = models.TextField()
    email = models.EmailField()
    number = models.CharField(max_length=20)
    address = models.CharField(max_length=100)
    linkedin = models.URLField()
    linkedin_pseudo = models.CharField(max_length=50)
    github = models.URLField()
    github_pseudo = models.CharField(max_length=50)
    

class Experience(models.Model):
    title = models.CharField(max_length=50)
    enterprise = models.CharField(max_length=50)
    date_begin = models.DateField()
    date_end = models.DateField()
    
    def __str__(self):
        return f"{self.title} / {self.enterprise}"
    
        
    def date(self):
        return f'{self.date_begin.strftime("%B %Y")}' + ('' if not self.date_end else f' - {self.date_end.strftime("%B %Y")}')

class ExperienceDetail(models.Model):
    category = models.ForeignKey(Experience, on_delete=models.CASCADE)
    content = models.CharField(max_length=100)
    
    def __str__(self):
        return f"{self.content}"

class CertificatCategory(models.Model):
    title = models.CharField(max_length=50)
    
    def __str__(self):
        return f"{self.title}"

class Certificat(models.Model):
    title = models.CharField(max_length=100)
    url = models.URLField()
    category = models.ForeignKey(CertificatCategory, on_delete=models.CASCADE)
    
    def __str__(self):
        return f"{self.title}"
 
class TechnicalSkillCategory(models.Model):
    title = models.CharField(max_length=50)
    
    def __str__(self):
        return f"{self.title}"

class TechnicalSkill(models.Model):
    title = models.CharField(max_length=50)
    category = models.ForeignKey(TechnicalSkillCategory, on_delete=models.CASCADE)
    
    def __str__(self):
        return f"{self.title}"

class SoftSkill(models.Model):
    title = models.CharField(max_length=50)
    
    def __str__(self):
        return f"{self.title}"

class Project(models.Model):
    title = models.CharField(max_length=50)
    # short_description = models.CharField(max_length=200)
    detail = models.TextField()
    # url = models.URLField(null=True, blank=True)
    image = models.ImageField(upload_to='images')
    def __str__(self):
        return f"{self.title}"

class Education(models.Model):
    title = models.CharField(max_length=100)
    school = models.CharField(max_length=100)
    date_begin = models.DateField()
    date_end = models.DateField(blank=True, null=True)
    
    def __str__(self):
        return f"{self.title}"
    
    def date(self):
        return f'{self.date_begin.strftime("%Y")}' + ('' if not self.date_end else f' - {self.date_end.strftime("%Y")}')
    

informations/views.py
from django.shortcuts import render
from .models import ProfessionnalProfile, Experience, CertificatCategory, TechnicalSkillCategory, SoftSkill, Project, Education


def home(request):
    template = 'informations/index.html'
    profile = ProfessionnalProfile.objects.first()
    certificate_categories = CertificatCategory.objects.all()
    soft_skills = SoftSkill.objects.all()
    technical_skill_categories = TechnicalSkillCategory.objects.all()
    educations = Education.objects.all()
    experiences = Experience.objects.all()
    projects = Project.objects.all()
    context = {
        "profile":profile,
        "certificate_categories":certificate_categories,
        "soft_skills": soft_skills,
        "technical_skill_categories": technical_skill_categories,
        "educations": educations,
        "experiences": experiences,
        "projects": projects,
    }
    
    return render(request, template, context)

templates/informations/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
   
    <meta name="description" content="Your description">
    <meta name="author" content="Your name">
	<meta property="og:site_name" content="" />
	<meta property="og:site" content="" />
	<meta property="og:title" content=""/>
	<meta property="og:description" content="" />
	<meta property="og:image" content="" />
	<meta property="og:url" content="" />

   
    <title>Mark Webpage Title</title>
    
   
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,400;0,600;0,700;1,400&family=Poppins:wght@600&display=swap' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'css/fontawesome-all.css' %}" rel="stylesheet">
	<link href="{% static 'css/styles.css' %}" rel="stylesheet">
	<link href="{% static 'css/custom.css' %}" rel="stylesheet">
	
</head>
<body data-spy="scroll" data-target=".fixed-top">
    
   
    <nav class="navbar navbar-expand-lg fixed-top navbar-dark">
        <div class="container">
            <a class="navbar-brand btn-outline-lg" href="index.html">N.S. Alfa</a>  
            <button class="navbar-toggler p-0 border-0" type="button" data-toggle="offcanvas">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="navbar-collapse offcanvas-collapse" id="navbarsExampleDefault">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link page-scroll" href="#header">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link page-scroll" href="#about">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link page-scroll" href="#certifications">Certifications</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link page-scroll" href="#skills">Skills</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link page-scroll" href="#projects">Projects</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link page-scroll" href="#path">Experience & Education</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link page-scroll" href="#contact">Contact</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
   


   
    <section id="header" class="header">
        <div class="center">
            <h1 class="text-pink">Hello world!</h1>
            <h4 class="text-light">ANDRIAMIFIDISOA Nomena Sombiniaina Alfa</h4>
            <p class="text-white">I am a penetration tester</p>
            <a href="mailto:{{profile.email}}" class="space-between">
                <span>Email :</span>
                <span>{{profile.email}}</span>
            </a>
            <a href="tel:{{profile.number}}" class="space-between">
                <span>Phone number : </span>
                <span>{{profile.number}}</span>
            </a>
        </div>
    </section>
   


   
    <section id="about" class="basic-2">
        <div class="container">
            <div class="row">
                <div class="col-6">
                    <img class="img img-fluid img-rounded" src="{% static 'images/photo.png' %}" alt="Me">
                </div>
                <div class="col-6 center">
                    <h2 class="h2-heading">About Me</h2>
                    <p>{{ profile.description }}</p>
                </div>
            </div>
        </div>
    </section>


    <section id="certifications" class="basic-2 bg-gray">
        <div class="container">
            <h2 class="h2-heading">Certifications</h2>
            <div class="row">
                
                {% for category in certificate_categories %}
                    <div class="col-4">
                        <h3>{{ category.title }}</h3>

                        <ul class="list-group">
                            {% for certificate in category.certificat_set.all %}
                                <li class="list-group-item list-group-item-action list-group-item-light">
                                    <a href="{{certificate.url}}">{{ certificate.title }}</a>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                {% endfor %}
                    
                
            </div>
        </div>
    </section>

    <section id="skills" class="basic-2">
        <div class="container">
            <h2 class="h2-heading">Skills</h2>
            <div class="row">
                <div class="col-lg-7">
                    <h3>Technical Skills</h3>
                    <ul class="list-group">
                        {% for category in technical_skill_categories %}
                            <li class="list-group-item list-group-item-action list-group-item-dark">
                                <h5>{{ category.title }}</h5>
                                <p>
                                    {% with category.technicalskill_set.all|join:", " as skills %}
                                        {{ skills }}
                                    {% endwith %}
                                </p>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="col-lg-5">
                    <h3>Soft Skills</h3>
                    <ul class="list-group">
                        {% for skill in soft_skills %}
                            <li class="list-group-item list-group-item-action list-group-item-dark center">
                                <p>{{ skill.title }}</p>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </section>



    <section id="projects" class="basic-2 bg-gray">
        <div class="container">
            <h2 class="h2-heading">Projects</h2>
            <div class="row">
                {% for project in projects %}
                    <div class="col-lg-6">
                        <div class="text-container">
                            <h3>{{ project.title }}</h3>
                            <div class="image-container center">
                                <img class="img-fluid" src="{{ project.image.url }}" alt="{{project.title}}">
                            </div>
                            <p>{{ project.detail}}</p>
                        </div>
                    </div>
                {% endfor %}
            </div>            
        </div>
    </section>


    <section id="path" class="basic-2">
        <div class="container">
            <h2 class="h2-heading">Experience & Education</h2>
            <div class="row">
                <div class="col-6">
                    <h3>Professional experience</h3>
                    
                    <ul class="list-group">
                        {% for experience in experiences %}
                            <li class="list-group-item list-group-item-action list-group-item-dark">
                                <h5 class="h5-heading">{{ experience.title}}</h5>
                                <h6 class="h5-heading">{{ experience.enterprise }}</h6>
                                <p>{{ experience.date }}</p>
                                <u>Tasks</u>
                                <ul>
                                    {% for detail in experience.experiencedetail_set.all %}
                                        <li>{{ detail }}</li>
                                    {% endfor %}
                                </ul>
                            </li>
                        {% endfor %}
                    </ul>
                    
                </div>
                <div class="col-6">
                    <h3>Academic Background</h3>
                    <ul class="list-group">
                    {% for education in educations %}
                        <li class="list-group-item list-group-item-action list-group-item-dark">
                            <h5>{{ education.title }}</h5>
                            <h6>{{ education.school }}</h6>
                            <p>{{ education.date }}</p>
                        </li>
                    {% endfor %}
                        
                    </ul>
                   
                </div>
            </div>
        </div>
    </section>

   
    <section id="contact" class="form-1 bg-gray">
        <div class="container">
           <h2>Contacts</h2>
            <ul class="list-group">
                <li class="list-group-item list-group-item-action list-group-item-light">
                    <a href="mailto:{{profile.email}}" class="space-between">
                        <span>Email :</span>
                        <span>{{profile.email}}</span>
                    </a>
                </li>
                <li class="list-group-item list-group-item-action list-group-item-light">
                    <a href="tel:{{profile.number}}" class="space-between">
                        <span>Phone number : </span>
                        <span>{{profile.number}}</span>
                    </a>
                </li>
                <li class="list-group-item list-group-item-action list-group-item-light">
                    <a href="{{profile.linkedin}}" class="space-between">
                        <span>Linkedin :  </span>
                        <span>Nomena Sombiniaina Alfa ANDRIAMIFIDISOA</span>
                    </a>
                </li>
                <li class="list-group-item list-group-item-action list-group-item-light">
                    <a href="{{profile.github}}" class="space-between">
                        <span>Github : </span>
                        <span>nomena-sombiniaina-alfa</span>
                    </a>
                </li>
                <li class="list-group-item list-group-item-action list-group-item-light">
                    <p class="space-between">
                        <span>Address : </span>
                        <span>{{ profile.address }}</span>
                    </p>
                </li>
            </ul>
        </div>
    </section>
   

    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.easing.min.js' %}"></script>
    <script src="{% static 'js/scripts.js' %}"></script>
</body>
</html>